zuul:
  routes:
    auth:
      path: /token/**
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    users:
      path: /users/**
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: auth
    signup:
      path: /signup
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: auth
    jobcenters:
      path: /api/centers/*
      stripPrefix: false
    jobs:
      path: /api/centers/*/jobs
      stripPrefix: false
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 20000

ribbon:  eager-load:    enabled: true
