# version: "3.2"
version: "2.1"

services:
  eurekaregistry:
    build:
      context: ../eurekaregistry
      dockerfile: eurekaregistry.Dockerfile
    image: eurekaregistry
    container_name: eurekaregistry
    environment:
      - SPRING_PROFILES_ACTIVE=peer1
      - LOGGING_LEVEL_COM_NETFLIX_DISCOVERY=DEBUG
    expose:
      - 8761
    ports:
      - 8761:8761
    networks:
      - progetto-tasd

  gateway:
    build:
      context: ../gateway
      dockerfile: gateway.Dockerfile
    image: gateway
    container_name: gateway
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - progetto-tasd
    depends_on:
      eurekaregistry:
        condition:
          service_started
    restart: on-failure

  authdb:
    image: postgres
    container_name: authdb
    environment:
      - POSTGRES_PASSWORD=1234
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - progetto-tasd
    healthcheck:
      test: "exit 0"

  auth:
    build:
      context: ../auth
      dockerfile: auth.Dockerfile
    image: auth
    container_name: auth
    expose:
      - 9100
    ports:
      - 9100:9100
    networks:
      - progetto-tasd
    depends_on:
      authdb:
        condition:
          service_healthy
      eurekaregistry:
        condition:
          service_started
      jobcenters:
        condition:
          service_started
      seekers:
        condition:
          service_started
    restart: on-failure

  centersdb:
    image: postgres
    container_name: centersdb
    environment:
      - POSTGRES_PASSWORD=1234
    expose:
      - 5432
    ports:
      - 5433:5432
    networks:
      - progetto-tasd
    healthcheck:
      test: "exit 0"

  jobcenters:
    build:
      context: ../jobcenters
      dockerfile: jobcenters.Dockerfile
    image: jobcenters
    container_name: jobcenters
    expose:
      - 8200
    ports:
      - 8200:8200
    networks:
      - progetto-tasd
    depends_on:
      centersdb:
        condition:
          service_healthy
      eurekaregistry:
        condition:
          service_started
    restart: on-failure

  jobsdb:
    image: postgres
    container_name: jobsdb
    environment:
      - POSTGRES_PASSWORD=1234
    expose:
      - 5432
    ports:
      - 5434:5432
    networks:
      - progetto-tasd
    healthcheck:
      test: "exit 0"

  jobs:
    build:
      context: ../jobs
      dockerfile: jobs.Dockerfile
    image: jobs
    container_name: jobs
    expose:
      - 8400
    ports:
      - 8400:8400
    networks:
      - progetto-tasd
    depends_on:
      jobsdb:
        condition:
          service_healthy
      eurekaregistry:
        condition:
          service_started
    restart: on-failure

  search:
    build:
      context: ../search
      dockerfile: search.Dockerfile
    image: search
    container_name: search
    expose:
      - 8500
    ports:
      - 8500:8500
    networks:
      - progetto-tasd
    depends_on:
      jobsdb:
        condition:
          service_healthy
      eurekaregistry:
        condition:
          service_started
    restart: on-failure

  seekersdb:
    image: postgres
    container_name: seekersdb
    environment:
      - POSTGRES_PASSWORD=1234
    expose:
      - 5432
    ports:
      - 5435:5432
    networks:
      - progetto-tasd
    healthcheck:
      test: "exit 0"

  seekers:
    build:
      context: ../seekers
      dockerfile: seekers.Dockerfile
    image: seekers
    container_name: seekers
    expose:
      - 8300
    ports:
      - 8300:8300
    networks:
      - progetto-tasd
    depends_on:
      seekersdb:
        condition:
          service_healthy
      eurekaregistry:
        condition:
          service_started
    restart: on-failure

  # adminer:
  #   image: adminer
  #   restart: always
  #   expose:
  #     - 8080
  #   networks:
  #     - progetto-tasd

networks:
  progetto-tasd:
    driver: host
